# Generated by Django 3.0.6 on 2020-05-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
