# Generated by Django 3.0.6 on 2020-05-20 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200520_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 5, 20, 8, 52, 21, 718578, tzinfo=utc)),
        ),
    ]
