# Generated by Django 3.0.6 on 2020-05-26 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200526_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 15, 14, 15, 512522, tzinfo=utc)),
        ),
    ]
