# Generated by Django 3.0.6 on 2020-05-27 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200527_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2020, 5, 27, 12, 39, 1, 874705, tzinfo=utc)),
        ),
    ]
