# Generated by Django 3.0.6 on 2020-05-14 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWatch',
            fields=[
                ('ordered_date', models.DateTimeField(default=datetime.datetime(2020, 5, 14, 16, 37, 0, 598759, tzinfo=utc))),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('zip_code', models.CharField(max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='product.Product')),
            ],
        ),
    ]
