# Generated by Django 3.0.6 on 2020-05-15 17:06

import datetime
import django.contrib.auth.models
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderwatch', '0002_auto_20200514_1638'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderwatch',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 17, 6, 50, 346307, tzinfo=utc)),
        ),
    ]
