# Generated by Django 3.0.6 on 2020-05-16 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderwatch', '0004_auto_20200515_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 13, 11, 59, 998664, tzinfo=utc)),
        ),
    ]
