# Generated by Django 3.0.6 on 2020-05-19 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderwatch', '0007_auto_20200517_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 13, 17, 38, 937168, tzinfo=utc)),
        ),
    ]
