# Generated by Django 3.0.6 on 2020-05-20 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderwatch', '0008_auto_20200519_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 6, 57, 11, 819504, tzinfo=utc)),
        ),
    ]
