# Generated by Django 3.0.6 on 2020-05-20 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orderwatch', '0010_auto_20200520_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 8, 52, 50, 185040, tzinfo=utc)),
        ),
    ]
