# Generated by Django 3.0.6 on 2020-05-26 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orderwatch', '0011_auto_20200520_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 15, 13, 41, 819842, tzinfo=utc)),
        ),
    ]
