# Generated by Django 3.0.6 on 2020-05-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200527_1202'),
        ('orderwatch', '0017_auto_20200527_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.OrderWatch'),
        ),
        migrations.DeleteModel(
            name='OrderWatch',
        ),
    ]
