# Generated by Django 3.0.6 on 2020-05-26 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0016_auto_20200526_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('ordered_date', models.DateTimeField(default=datetime.datetime(2020, 5, 26, 15, 13, 41, 817119, tzinfo=utc))),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('zip_code', models.CharField(max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordercart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.OrderCart')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
