# Generated by Django 3.0.6 on 2020-05-27 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_auto_20200526_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordercart',
        ),
        migrations.AlterField(
            model_name='ordercart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 8, 50, 23, 200312, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordered_date', models.DateTimeField(default=datetime.datetime(2020, 5, 27, 8, 50, 23, 202972, tzinfo=utc))),
                ('ordercart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.OrderCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
