# Generated by Django 3.0.6 on 2020-05-27 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_auto_20200527_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 12, 2, 34, 421987, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='OrderWatch',
            fields=[
                ('ordered_date', models.DateTimeField(default=datetime.datetime(2020, 5, 27, 12, 2, 34, 419347, tzinfo=utc))),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('zip_code', models.CharField(max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='ordercart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.OrderWatch'),
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
    ]
