# Generated by Django 3.0.6 on 2020-05-27 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200527_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 12, 39, 1, 878740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 12, 39, 1, 876157, tzinfo=utc)),
        ),
    ]
