# Generated by Django 3.0.6 on 2020-05-27 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200527_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 13, 33, 5, 778433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 13, 33, 5, 775930, tzinfo=utc)),
        ),
    ]
