# Generated by Django 3.0.6 on 2020-05-27 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200527_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwatch',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderwatch',
            name='order_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderwatch',
            name='order_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderwatch',
            name='order_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 15, 18, 47, 551190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 15, 18, 47, 548431, tzinfo=utc)),
        ),
    ]
