# Generated by Django 3.0.6 on 2020-05-27 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200527_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderwatch',
            name='order_cancelled',
        ),
        migrations.RemoveField(
            model_name='orderwatch',
            name='order_delivered',
        ),
        migrations.RemoveField(
            model_name='orderwatch',
            name='order_refund',
        ),
        migrations.RemoveField(
            model_name='orderwatch',
            name='order_returned',
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 22, 4, 971105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderwatch',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 16, 22, 4, 965131, tzinfo=utc)),
        ),
    ]
