# Generated by Django 3.0.6 on 2020-05-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200506_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
