# Generated by Django 3.0.6 on 2020-05-12 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 7, 22, 29, 676941, tzinfo=utc)),
        ),
    ]
