# Generated by Django 3.0.6 on 2020-05-12 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200512_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 7, 26, 2, 388775, tzinfo=utc)),
        ),
    ]
