# Generated by Django 3.0.6 on 2020-05-12 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200512_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 7, 27, 18, 647606, tzinfo=utc)),
        ),
    ]
